name: Build Binary
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Save Result
        uses: actions/upload-artifact@v3
        with:
          name: my-binary
          path: build/cg_workspace
