name: Build Binary
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download your code onto the runner
      - uses: actions/checkout@v6 
      
      # Step 2: Install dependencies (JSON library)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      # Step 3: Run the Build
      - name: Compile
        run: |
          # Create a separate folder for the build files
          mkdir -p build
          # -S . means look for CMakeLists.txt in the CURRENT folder
          # -B build means put the output in the build folder
          cmake -S . -B build
          # Compile the code
          cmake --build build

      # Step 4: Save the result as a downloadable zip
      - name: Save Result
        uses: actions/upload-artifact@v7
        with:
          name: cg-workspace-binary
          # This must match the name of the executable set in CMakeLists.txt
          path: build/cg_workspace
